version: '3.3'
services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  rabbitmq:
    image: rabbitmq:alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
  django_app:
    build: 
      context: django_app
      dockerfile: Dockerfile
    command: uwsgi --ini black_hole.uwsgi.ini --http :8000
  parsing_microservice:
    build:
      context: parsing_microservice
      dockerfile: Dockerfile
    command: python main.py

